### ISSUE TITLE
Request: Please Make Configure Options For Minimal Install

### ISSUE THREAD

**Issue by ghost** [vrtadmin/clamav-devel#14]
Hi,

For those concerned with the development of clamav, first thank you for such a great app and great job!

I'd like to ask that the clamav developers PLEASE consider adding in ./configure --options so that the end-user can compile clamav as just a basic on demand scanner, for the $HOME user, that might typically only want to use clamav to scan with on occassion.

I personally only need clamav as an on demand scanner to scan my files, folders and box on ocassion.

I hope the developers will PLEASE really consider this and add in options in the future.

In the meantime I edited the Makefile.am and changed it like this;

SUBDIRS = libltdl libclamav clamscan freshclam sigtool clamconf database docs etc test clambc unit_tests

Would that for now statisfy for the basics of just having an on demand scanner, or is there something else I can remove?

Thank you for your time and consideration! :)

**Comment by moulei** [comment]
After compiling clamav, minus the /doc & man /paths this is the contents of my clamav pkg;

var/
var/run/
var/run/clamav/
var/log/
var/log/clamav/
var/log/clamav/freshclam.log.new
var/log/clamav/clamd.log.new
var/lib/
var/lib/clamav/
var/lib/clamav/daily.cvd
var/lib/clamav/main.cvd
etc/
etc/logrotate.d/
etc/logrotate.d/clamav.new
etc/rc.d/
etc/rc.d/rc.clamav.new
etc/freshclam.conf.new
etc/clamd.conf.sample
usr/sbin/
usr/sbin/clamd
usr/bin/
usr/bin/clamscan
usr/bin/clamdscan
usr/bin/freshclam
usr/bin/sigtool
usr/bin/clamconf
usr/bin/clamdtop
usr/bin/clambc
usr/bin/clamsubmit
usr/bin/clamav-config
usr/include/
usr/include/clamav.h
usr/lib64/
usr/lib64/libclamunrar.so.6.1.22
usr/lib64/libclamunrar_iface.so.6.1.22
usr/lib64/libclamav.so.6.1.22
usr/lib64/pkgconfig/
usr/lib64/pkgconfig/libclamav.pc
usr/lib64/libclamav.la
usr/lib64/libclamunrar_iface.la
usr/lib64/libclamunrar.la

I noticed this compiled in clamd and clamdtop even though I removed them from the SUBDIRS.
If I'm only compiling for an on demand scanner do I need the clamd?

I don't need clamdtop for just a scanner do I? I thought since I removed it from teh SUBDIRS it would be gone also?

THANKS again :)

**Comment by moulei** [comment]
Hi,

Has anyone had a chance to see this?

I should of made the Post Title; I need options for minimal install...

I really want to figure this out as soon as possible so I can compile and install clamav.

thank you

**Comment by moulei** [comment]
Hi,

Has anyone seen this, or is this even the right place to ask this in regards to Clamav?

Is this clamav's GIthub?

thank you

**Comment by AlexanderS** [comment]
Did you execute ``autoreconf`` after changing the Makefile.am?

**Comment by moulei** [comment]
You're late to the party, LOL...

Anyhow I've played with it and made a mini install, but it still bitched about things when doing an update, but no biggie, it all worked...

As a Geek and Linux user, only using Linux on a laptop for personal usage, I have no need for all the other things in Clamav, excpet the ability to do on demand scans when needed.

It would certainly be great in the future if the Clamav team just made a basic install for this need.

Afterall, even in the Windows world you can do basic installs of AV apps, hehe... :) Pretty sad we don't have this ability in Linux with ```./configure --options``` to do so...

**Comment by chadmyers** [comment]
+1 on this issue/concept.  I'm looking at making an AWS Lambda service that runs clamav on a file in AWS S3 (a sort of virus-scan-as-a-service concept) but AWS Lambda's linux image doesn't have clamav installed already, so I have to include a self-contained/portable clamscan distribution to drop in the Lambda container to execute. So I'm trying to do something similar to what @ghost is doing

**Comment by chadmyers** [comment]
@ghost  Follow up -- it turns out this was super easy.

All I needed was to be able to call `clamsacn` on a system where clamav was not installed (i.e. AWS Lambda -- doesn't let you install packages).

All you need to do is install clam av on a fresh VM and then copy these files:

 - /usr/bin/clamscan (the executable)
 - /usr/lib64/libclamav.so.6
 - /usr/lib64/libclamav.so.6.1.26

I copied those, zipped them and moved them to another system that didn't have ClamAV installed at all (no clamd, no clamscan, nothing).

 - Unzip those three files into a folder (I put them in ~/clamchad)
 - Download the [main.cvd](http://database.clamav.net/main.cvd) and [daily.cvd](http://database.clamav.net/daily.cvd) virus defs from the webiste to ~/clamchad/db
 - `cd ~/clamchad`
 - `chmod 755 ~/clamchad/clamscan`
 - `export LD_LIBRARY_PATH=/home/ec-2user/clamchad/clamscan`
 - `./clamscan  --stdout -d ~/clamchad/db/ file-to-scan.txt`

**Comment by steve-morgan** [comment]
Hi,

Tracking this feature request at https://bugzilla.clamav.net/show_bug.cgi?id=11423.

**Comment by vrtadmin** [comment]
Moved to bugzilla.
