### ISSUE TITLE
Doc/Example mis-match on subsignature modifiers..

### ISSUE THREAD

**Issue by wmetcalf** [vrtadmin/clamav-devel#33]
3.2.8 Subsignature Modifiers
ClamAV (clamav-0.99) supports a number of additional subsignature modifiers
for logical signatures. This is done by specifying ’::’ followed by a number of
characters representing the desired options.

clamscan blows up with the examples provided in the docs...

clamav-nocase-A;Target:0;0&1;41414141/i;424242424242/i
-matches ’AAAA’(nocase) and ’BBBBBB’(nocase)

should be in the format of...

clamav-nocase-A;Target:0;0&1;41414141::i;424242424242::i
-matches ’AAAA’(nocase) and ’BBBBBB’(nocase)

**Comment by kevlin2** [comment]
You're absolutely correct. The examples were generated with an earlier 0.99 build of ClamAV which used the signature convention in the examples. However, due to conflicts with the PCRE subsig format, the delimiter was changed.

The issue has been solved with commit clamav-0.99-beta1-249-g8c04254 (master) on Thu Nov 12 10:33:10 2015 -0500.

Thanks for noticing the issue and contributing to the project!
